import { Card } from './types';

type CardWithoutId = Omit<Card, 'id'>;

export const SEED: CardWithoutId[] = [
  {
    type: 'FACT',
    title: 'Cuerpo humano',
    content: 'Tu **ADN** estirado mediría dos veces la distancia de la Tierra al Sol.',
    answer: '',
    refCode: 'A20',
    active: true,
    frequency: 'HIGH',
  },
  {
    type: 'HISTORY',
    title: 'Hildegarda de Bingen',
    content: 'En el **siglo XII** una monja escribió tratados de medicina, compuso música y dirigió un monasterio.',
    answer: '',
    refCode: 'H07',
    active: true,
    frequency: 'MEDIUM',
  },
  {
    type: 'QUOTE',
    title: 'Santa Teresa de Jesús',
    content: 'Nada te **turbe**, nada te espante; quien a Dios tiene, nada le falta.',
    answer: '',
    refCode: 'Q11',
    active: true,
    frequency: 'MEDIUM',
  },
  {
    type: 'QUIZ',
    title: 'Sacramentos',
    content: '¿Cuántos **sacramentos** reconoce la Iglesia Católica?',
    answer: 'Siete: Bautismo, Confirmación, Eucaristía, Reconciliación, Unción, Orden y Matrimonio.',
    refCode: 'Z03',
    active: true,
    frequency: 'HIGH',
  },
  {
    type: 'FACT',
    title: 'Abejas',
    content: 'Las **abejas** pueden aprender a reconocer rostros humanos.',
    answer: '',
    refCode: 'A41',
    active: true,
    frequency: 'MEDIUM',
  },
  {
    type: 'QUIZ',
    title: 'Sistema solar',
    content: '¿Qué planeta tiene los **anillos** más visibles desde la Tierra?',
    answer: 'Saturno — sus anillos son visibles incluso con un telescopio pequeño.',
    refCode: 'Z08',
    active: true,
    frequency: 'MEDIUM',
  },
  {
    type: 'HISTORY',
    title: 'Marie Curie',
    content: 'Fue la **primera** persona en ganar dos Premios Nobel, en Física y Química.',
    answer: '',
    refCode: 'H22',
    active: true,
    frequency: 'HIGH',
  },
  {
    type: 'QUOTE',
    title: 'San Agustín',
    content: 'Nos hiciste, Señor, para Ti, y nuestro **corazón** está inquieto hasta que descanse en Ti.',
    answer: '',
    refCode: 'Q24',
    active: true,
    frequency: 'LOW',
  },
  {
    type: 'FACT',
    title: 'Cosmos',
    content: 'Una **galaxia** promedio contiene cien mil millones de estrellas.',
    answer: '',
    refCode: 'A55',
    active: true,
    frequency: 'MEDIUM',
  },
  {
    type: 'HUMOR',
    title: 'Chiste de ciencia',
    content: '¿Qué le dijo un **electrón** a otro? Voy con cargas pesadas.',
    answer: '',
    refCode: 'X02',
    active: true,
    frequency: 'LOW',
  },
];
